apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  type: {{ .Values.services.backend.type }}
  ports:
  - port: {{ .Values.services.backend.port }}
    targetPort: 8000
  selector:
    app: backend
