apiVersion: v1
kind: Service
metadata:
  name: redis-svc
spec:
  type: {{ .Values.services.redis.type }}
  ports:
  - port: {{ .Values.services.redis.port }}
    targetPort: 6379
  selector:
    app: redis
