apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: {{ .Values.redis.servicePort }}
      targetPort: {{ .Values.redis.servicePort }}
