replicaCount: 1

images:
  backend: shreybatra/sample-backend
  frontend: shreybatra/sample-frontend
  redis: redis

services:
  backend:
    type: ClusterIP
    port: 8000
  frontend:
    type: NodePort
    port: 5173
    nodePort: 31000
  redis:
    type: ClusterIP
    port: 6379

env:
  redisUri: redis://redis-svc:6379
  backendUrl: http://backend-svc:8000


